- hosts: li-uat-01
  user: deploy
  vars:
    web_dir: '/home/deploy/sites'
    app_version: 'uat'
    app_env: 'uat'
    app_name: 'abnormalloads'
    app_port: 8312
    db_name: 'abnormalloads_uat'
    db_host: 'localhost'
    server_address: 'test-beta.abloads.co.uk'
  roles:
    - ../../common/roles/restoredb
    - ../../common/roles/upgradedb
