module.exports = (dal) ->
  modelDefinition =
    name: 'Load'
    schemaDefinition:
      systemId: 'ObjectId'
      name: 'String'
      vehicleLength: 'String'
      front: 'String'
      rear: 'String'
      length: 'String'
      width: 'String'
      height: 'String'
      grossWeight: 'String'
      weight1: 'Integer'
      weight2: 'Integer'
      weight3: 'Integer'
      weight4: 'Integer'
      weight5: 'Integer'
      weight6: 'Integer'
      weight7: 'Integer'
      weight8: 'Integer'
      weight9: 'Integer'
      weight10: 'Integer'
      space1to2: 'String'
      space2to3: 'String'
      space3to4: 'String'
      space4to5: 'String'
      space5to6: 'String'
      space6to7: 'String'
      space7to8: 'String'
      spae8to9: 'String'
      space9to10: 'String'
      wheels1: 'String'
      wheels2: 'String'
      wheels3: 'String'
      wheels4: 'String'
      wheels5: 'String'
      wheels6: 'String'
      wheels7: 'String'
      wheels8: 'String'
      wheels9: 'String'
      wheels10: 'String'
      aka: 'String'
    options:
      collection: 'Loads'

  modelDefinition.schema = dal.schemaFactory modelDefinition
  model = dal.modelFactory modelDefinition
  dal.crudFactory model
